changed 'cho' to 'echo'

diff --git a/data-release/wikipathways-data-release b/data-release/wikipathways-data-release
--- a/data-release/wikipathways-data-release
+++ b/data-release/wikipathways-data-release
@@ -147,17 +147,17 @@ fi
 
 OUT="$RDF_DIR"/wikipathways-"$DATE"-rdf-gpml.zip
 if ! wget --no-check-certificate https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20RDF%20-%20Monthly/lastSuccessfulBuild/artifact/WP2RDF/output/wikipathways-rdf-gpml.zip -O "$OUT"; then
-        cho "ERROR: Can't get file" >&2
+        echo "ERROR: Can't get file" >&2
 fi
 
 OUT="$RDF_DIR"/wikipathways-"$DATE"-rdf-wp.zip
 if ! wget --no-check-certificate https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20RDF%20-%20Monthly/lastSuccessfulBuild/artifact/WP2RDF/output/wikipathways-rdf-wp.zip -O "$OUT"; then
-        cho "ERROR: Can't get file" >&2
+        echo "ERROR: Can't get file" >&2
 fi
 
 OUT="$RDF_DIR"/wikipathways-"$DATE"-rdf-void.ttl
 if ! wget --no-check-certificate https://jenkins.bigcat.unimaas.nl/job/WikiPathways%20RDF%20-%20Monthly/lastSuccessfulBuild/artifact/WP2RDF/output/void_for_data.wp.org.ttl -O "$OUT"; then
-        cho "ERROR: Can't get file" >&2
+        echo "ERROR: Can't get file" >&2
 fi
 
 # remake current dir with symlinks and special index.php for gpmls
